'use client';

import { useMemo, useState } from 'react';
import { Download, HelpCircle } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { appointmentChecklists } from '@/lib/mockData';

const documents = [
  'Aadhar card / photo ID',
  'Previous reports (X-ray, MRI, blood tests)',
  'Current medication list',
  'Insurance card (if applicable)',
  'Doctor referral letter (if available)',
];

const forms = [
  'Patient Registration Form',
  'Medical History Declaration',
  'Consent for Surgery Form',
  'Insurance Pre-authorization Form',
];

interface AppointmentGuideProps {
  procedure: string;
}

export function AppointmentGuide({ procedure }: AppointmentGuideProps) {
  const sourceChecklist = useMemo(() => {
    return appointmentChecklists[procedure as keyof typeof appointmentChecklists] ?? {
      documents,
      questions: [
        `What are my treatment options for ${procedure}?`,
        'What is included in the package estimate and what is not?',
        'How do my comorbidities affect risk and recovery?',
        'How many follow-ups and physiotherapy sessions are expected?',
      ],
      forms,
    };
  }, [procedure]);

  const [checked, setChecked] = useState<Record<string, boolean>>({});

  const downloadTemplate = (formName: string) => {
    const content = [
      formName,
      '---',
      'Patient Name:',
      'Age / Gender:',
      'Hospital:',
      `Procedure: ${procedure}`,
      'Date:',
      'Notes:',
      '',
      'Generated by HealthNav for appointment preparation.',
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${formName.toLowerCase().replace(/\s+/g, '-')}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const downloadChecklist = () => {
    const lines = [
      `HealthNav Appointment Checklist`,
      `Procedure: ${procedure}`,
      '',
      'Documents to carry:',
      ...sourceChecklist.documents.map((item: string) => `- ${item}${checked[item] ? ' [checked]' : ''}`),
      '',
      'Questions to ask the doctor:',
      ...sourceChecklist.questions.map((item: string) => `- ${item}`),
      '',
      'Common forms:',
      ...sourceChecklist.forms.map((item: string) => `- ${item}`),
      '',
      'Generated by HealthNav. Decision support only.',
    ];

    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `healthnav-appointment-checklist-${procedure.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const askForMoreHelp = async () => {
    const prompt = `Help me prepare for my ${procedure} appointment. Include documents, questions, and financial prep tips.`;
    await navigator.clipboard.writeText(prompt);
  };

  return (
    <div className="rounded-xl border border-border bg-card p-4">
      <p className="text-sm font-semibold">Appointment &amp; Paperwork Assistant</p>
      <p className="mt-1 text-xs text-muted-foreground">
        Procedure-specific checklist to reduce surprises on appointment day.
      </p>
      <div className="mt-3 space-y-2">
        {sourceChecklist.documents.map((item: string) => (
          <label key={item} className="flex items-center gap-2 text-sm">
            <Checkbox
              checked={!!checked[item]}
              onCheckedChange={(next) =>
                setChecked((prev) => ({ ...prev, [item]: Boolean(next) }))
              }
            />
            <span>{item}</span>
          </label>
        ))}
      </div>
      <p className="mt-4 text-sm font-medium">Questions to ask your doctor</p>
      <div className="mt-2 space-y-1 text-sm text-muted-foreground">
        {sourceChecklist.questions.map((question: string) => (
          <p key={question}>- {question}</p>
        ))}
      </div>

      <p className="mt-4 text-sm font-medium">Common forms you may need</p>
      <div className="mt-2 space-y-2">
        {sourceChecklist.forms.map((form: string) => (
          <div key={form} className="flex items-center justify-between gap-2 rounded-md border border-border px-3 py-2">
            <span className="text-sm text-muted-foreground">{form}</span>
            <Button size="sm" variant="outline" onClick={() => downloadTemplate(form)}>
              Generate
            </Button>
          </div>
        ))}
      </div>

      <div className="mt-4 flex flex-wrap gap-2">
        <Button size="sm" variant="outline" onClick={downloadChecklist}>
          <Download className="mr-1 h-4 w-4" />
          Download Checklist
        </Button>
        <Button size="sm" onClick={askForMoreHelp}>
          <HelpCircle className="mr-1 h-4 w-4" />
          Ask AI for More Help
        </Button>
      </div>
    </div>
  );
}
