'use client';

import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';

const documents = [
  'Aadhar card / photo ID',
  'Previous reports (X-ray, MRI, blood tests)',
  'Current medication list',
  'Insurance card (if applicable)',
  'Doctor referral letter (if available)',
];

const forms = [
  'Patient Registration Form',
  'Medical History Declaration',
  'Consent for Surgery Form',
  'Insurance Pre-authorization Form',
];

interface AppointmentGuideProps {
  procedure: string;
}

export function AppointmentGuide({ procedure }: AppointmentGuideProps) {
  const questions = [
    `What are my treatment options for ${procedure}?`,
    'What is included in the package estimate and what is not?',
    'How do my comorbidities affect risk and recovery?',
    'How many follow-ups and physiotherapy sessions are expected?',
  ];

  const downloadTemplate = (formName: string) => {
    const content = [
      formName,
      '---',
      'Patient Name:',
      'Age / Gender:',
      'Hospital:',
      `Procedure: ${procedure}`,
      'Date:',
      'Notes:',
      '',
      'Generated by HealthNav for appointment preparation.',
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${formName.toLowerCase().replace(/\s+/g, '-')}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="rounded-xl border border-border bg-card p-4">
      <p className="text-sm font-semibold">Before Your Appointment</p>
      <div className="mt-3 space-y-2">
        {documents.map((item) => (
          <label key={item} className="flex items-center gap-2 text-sm">
            <Checkbox />
            <span>{item}</span>
          </label>
        ))}
      </div>
      <p className="mt-4 text-sm font-medium">Questions to ask your doctor</p>
      <ul className="mt-2 space-y-1 text-sm text-muted-foreground">
        {questions.map((question) => (
          <li key={question}>{question}</li>
        ))}
      </ul>

      <p className="mt-4 text-sm font-medium">Common forms you may need</p>
      <div className="mt-2 space-y-2">
        {forms.map((form) => (
          <div key={form} className="flex items-center justify-between gap-2 rounded-md border border-border px-3 py-2">
            <span className="text-sm text-muted-foreground">{form}</span>
            <Button size="sm" variant="outline" onClick={() => downloadTemplate(form)}>
              Generate
            </Button>
          </div>
        ))}
      </div>

      <div className="mt-4 flex gap-2">
        <Button size="sm" variant="outline">Download Checklist PDF</Button>
        <Button size="sm">Ask AI for More Help</Button>
      </div>
    </div>
  );
}
